### ISSUE TITLE
Cannot set property 'siteUrl' of undefined

### ISSUE THREAD

**Issue by x5engine** [PoBuchi/pauli-linkedin-config-ui#2]
I got this error today when trying to use your package but I am totally confused because you're loading all the api key and secret on the client ? is that normal?

linkedin-configure.js:1 Uncaught TypeError: Cannot set property 'siteUrl' of undefined
    at linkedin-configure.js (linkedin-configure.js:1)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at require (modules-runtime.js?hash=2b888cb…:130)
    at pauli_linkedin-config-ui.js?hash=2ce01de…:76
    at pauli_linkedin-config-ui.js?hash=2ce01de…:82

and where do you I set the api keys?

settings.json?

thank you

**Comment by calebebrim** [comment]
Having the same issue here

**Comment by PoBuchi** [comment]
@meteorplus you are setting api key in server code only!!!

```
ServiceConfiguration.configurations.upsert(
  { service: 'linkedin' },
  {
    $set: {
      service: 'linkedin',
      clientId: 'xxxxxxxx',
      secret: 'xxxxxxxxx',
    },
  },
);
```
